scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  startBlock: 1058931
  ethereum:
    jsonRpcUrl: "http://54.191.199.113:8545"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "openzeppelin/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "http://54.191.199.113:8545"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"
    imageHash: "sha256:efeb2a41008333d9fc266e274fa84dec8cce50b5765aa25370a942255bbb1013"

log:
  level: debug
