scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  chainId: 1
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "openzeppelin/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"
    imageHash: "sha256:a0f49d3a5f3f14909309f3d7bd89b0adf4f9bbb4e7c08fee8c39975bf77afca0"

log:
  level: debug
