# This file is used by the development server (on AWS)
scanner:
  scannerImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-scanner:latest"
  chainId: 1
  #startBlock: 11792184
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "http://eth-internal.fortify-dev.com:8545"

query:
  queryImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "http://eth-internal.fortify-dev.com:8545"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"
    imageHash: "sha256:d2edd2040544eba5c46f539b45684742bf71f010067469e588af2b8e90ddacdd"

log:
  level: info
  maxLogSize: 10m
  maxLogFiles: 10