# This file is used by the development server (on AWS)
# GITHUB_HASH is replaced on the server at deploy time

registry:
  ethereum:
    websocketUrl: "REGISTRY_WSS_URL"
    jsonRpcUrl: "REGISTRY_API_URL"
  contractAddress: "0x1Ad235EF22Dd15d291ecD4b44a5739aD4F61b3A5"
  containerRegistry: disco.forta.network
  username: discouser
  password: discopass

scanner:
  scannerImage: "ECR_REGISTRY/forta-scanner:GITHUB_HASH"
  chainId: 1
  #startBlock: 12860865
  #endBlock: 11792184
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

json-rpc-proxy:
  jsonRpcImage: "ECR_REGISTRY/forta-json-rpc:GITHUB_HASH"
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

trace:
  enabled: true
  ethereum:
    jsonRpcUrl: "ALCHEMY_URL"

query:
  queryImage: "ECR_REGISTRY/forta-query:GITHUB_HASH"
  port: 8778
  publishTo:
    batch:
      sendEmpty: false
      intervalSeconds: 15
      maxAlerts: 100
    contractAddress: "0xf4746faBc1D5E751248Ea3AC87ceB13C432F0C1A"
    ipfs:
      gatewayUrl: "http://ipfs.forta.internal:5001"
    ethereum:
      jsonRpcUrl: "REGISTRY_API_URL"
      contractAddress: "0x38C1e080BeEb26eeA91932178E62987598230271"
  db:
    path: "/tmp/forta-alerts"

log:
  level: info
  maxLogSize: 50m
  maxLogFiles: 10
