# This file is used by the development server (on AWS)
# GITHUB_HASH is replaced on the server at deploy time

registry:
  ethereum:
    websocketUrl: "wss://eth-goerli.alchemyapi.io/v2/-rwVPKLYyChGSdep0hDHOaKOCOCVwmJr"
    jsonRpcUrl: "https://eth-goerli.alchemyapi.io/v2/-rwVPKLYyChGSdep0hDHOaKOCOCVwmJr"
  contractAddress: "0xBD7F842Cb96dFF147d6b9b4c9f8e56acF76A969B"
  containerRegistry: disco.forta.network
  poolId: "0x9d3d1df113ae5f4ff7fb542439229d50a384f4c2162c4fe4e298beefc872ddf2"

scanner:
  scannerImage: "ECR_REGISTRY/fortify-scanner:GITHUB_HASH"
  chainId: 1
  #startBlock: 12860865
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

json-rpc-proxy:
  jsonRpcImage: "ECR_REGISTRY/fortify-json-rpc:GITHUB_HASH"
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

trace:
  enabled: true
  ethereum:
    jsonRpcUrl: "ALCHEMY_URL"

query:
  queryImage: "ECR_REGISTRY/fortify-query:GITHUB_HASH"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

log:
  level: info
  maxLogSize: 50m
  maxLogFiles: 10
