scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "openzeppelin/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"
    imageHash: "sha256:766277b009bf504d274a976a24a31bedfe0b2df92c1a4299b06cfdfdd241d516"

log:
  level: debug
