scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  db:
    path: "/tmp/fortify-alerts"
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"

log:
  level: info
