registry:
  jsonRpcUrl: "https://arb-rinkeby.g.alchemy.com/v2/YxokkWMvqmvGoOgc0XqnJXpZ5pz7pPgf"
  contractAddress: "0xd5180d374b6d1961BA24D0a4Dbf26d696fda4cad"
  containerRegistry: disco-dev.forta.network
  poolId: "0xe95fb42f3bcc321b535f505adf41f27f2f7edbce3f4febeffc1b38c4f8adbc64"

#registry:
#  jsonRpcUrl: "http://localhost:8545"
#  contractAddress: "0x5fbdb2315678afecb367f032d93f642f64180aa3"
#  containerRegistry: localhost:1970 # Local Disco
#  poolId: "123"

scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  chainId: 1
  #startBlock: 11792184
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "openzeppelin/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

trace:
  enabled: true
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"
log:
  level: debug
  maxLogSize: 10m
  maxLogFiles: 10
