# This file is used by the development server (on AWS)
# GITHUB_HASH is replaced on the server at deploy time

registry:
  ethereum:
    websocketUrl: "REGISTRY_WSS_URL"
    jsonRpcUrl: "REGISTRY_API_URL"
  containerRegistry: disco-dev.forta.network
  username: discouser
  password: discopass
  ipfsGateway: "https://ipfs.infura.io"

scanner:
  chainId: 1
  #startBlock: 12860865
  #endBlock: 11792184
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

jsonRpcProxy:
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

trace:
  enabled: true
  ethereum:
    jsonRpcUrl: "ALCHEMY_URL"

query:
  port: 8778
  publishTo:
    batch:
      skipEmpty: true
      intervalSeconds: 15
      maxAlerts: 100
    ipfs:
      gatewayUrl: "http://ipfs.forta.internal:5001"
    ethereum:
      jsonRpcUrl: "REGISTRY_API_URL"
  db:
    path: "/tmp/forta-alerts"

log:
  level: info
  maxLogSize: 50m
  maxLogFiles: 10

ens:
  ethereum:
    jsonRpcUrl: "REGISTRY_API_URL"
