scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  chainId: 1
  #startBlock: 11792184
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "openzeppelin/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "http://eth.fortify-dev.com:8545"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"
    imageHash: "sha256:2c1304243b69a7daea49d5b62b9a4b589b5378299c9f9ffb62ba12178f425787"
#  - name: "flash-loans"
#    image: "openzeppelin/lab-flash-loans:latest"
#    imageHash: "sha256:b33c53cbbf29faa3511d4e339288e3d86d290771535d3dcd15f8ba23d7c91a99"

log:
  level: debug
  maxLogSize: 10m
  maxLogFiles: 10