# This file is used by the development server (on AWS)
# GITHUB_HASH is replaced on the server at deploy time
scanner:
  scannerImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-scanner:GITHUB_HASH"
  chainId: 1
  #startBlock: 11792184
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "http://eth-internal.fortify-dev.com:8545"

query:
  queryImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-query:GITHUB_HASH"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-json-rpc:GITHUB_HASH"
  ethereum:
    jsonRpcUrl: "http://eth-internal.fortify-dev.com:8545"

agents:
  - name: "example-agent"
    image: "openzeppelin/fortify-agent:latest"
    imageHash: "sha256:a0c99d9906afb9c0f418bf6f9a825aee8637dd498974212d212fa1a7470752ae"

log:
  level: info
  maxLogSize: 10m
  maxLogFiles: 10