registry:
  ethereum:
    websocketUrl: "wss://eth-goerli.alchemyapi.io/v2/-rwVPKLYyChGSdep0hDHOaKOCOCVwmJr"
    jsonRpcUrl: "https://eth-goerli.alchemyapi.io/v2/-rwVPKLYyChGSdep0hDHOaKOCOCVwmJr"
  contractAddress: "0x30dB6Af76Ff4A9A30d7f927eFab235a7ea600e22"
  containerRegistry: disco-dev.forta.network
  poolId: "0x9d3d1df113ae5f4ff7fb542439229d50a384f4c2162c4fe4e298beefc872ddf2"

#registry:
#  jsonRpcUrl: "http://localhost:8545"
#  contractAddress: "0x5fbdb2315678afecb367f032d93f642f64180aa3"
#  containerRegistry: localhost:1970 # Local Disco
#  poolId: "123"

scanner:
  scannerImage: "openzeppelin/fortify-scanner:latest"
  chainId: 1
  #startBlock: 11792184
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

query:
  queryImage: "openzeppelin/fortify-query:latest"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "openzeppelin/fortify-json-rpc:latest"
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

trace:
  enabled: false
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"
log:
  level: debug
  maxLogSize: 10m
  maxLogFiles: 10
