zephyr:
  nodeImage: "openzeppelin/zephyr-node:latest"

ethereum:
  jsonRpcUrl: "https://cloudflare-eth.com"

agents:
  - name: "example1"
    image: "openzeppelin/zephyr-agent:latest"
  - name: "example2"
    image: "openzeppelin/zephyr-agent:latest"
  - name: "example3"
    image: "openzeppelin/zephyr-agent:latest"

log:
  level: info
