# This file is used by the development server (on AWS)
# GITHUB_HASH is replaced on the server at deploy time
scanner:
  scannerImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-scanner:GITHUB_HASH"
  chainId: 1
  #startBlock: 11792184
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "http://eth-internal.fortify-dev.com:8545"

query:
  queryImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-query:GITHUB_HASH"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

json-rpc-proxy:
  jsonRpcImage: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-json-rpc:GITHUB_HASH"
  ethereum:
    jsonRpcUrl: "http://eth-internal.fortify-dev.com:8545"

agents:
  - name: "high-gas"
    image: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-agent-lab:high-gas-9ebdb8de0ea28460d42910020d7f1f1acd3eb2f5"
  - name: "ownership-change"
    image: "997179694723.dkr.ecr.us-west-2.amazonaws.com/fortify-agent-lab:ownership-change-9ebdb8de0ea28460d42910020d7f1f1acd3eb2f5"

log:
  level: info
  maxLogSize: 10m
  maxLogFiles: 10
