# This file is used by the development server (on AWS)
# GITHUB_HASH is replaced on the server at deploy time

registry:
  jsonRpcUrl: "https://arb-rinkeby.g.alchemy.com/v2/YxokkWMvqmvGoOgc0XqnJXpZ5pz7pPgf"
  contractAddress: "0xd5180d374b6d1961BA24D0a4Dbf26d696fda4cad"
  containerRegistry: DISCO_URL
  poolId: "0xe95fb42f3bcc321b535f505adf41f27f2f7edbce3f4febeffc1b38c4f8adbc64"

scanner:
  scannerImage: "ECR_REGISTRY/fortify-scanner:GITHUB_HASH"
  chainId: 1
  startBlock: 12752475
  #endBlock: 11792184
  #disableTracing: true
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

json-rpc-proxy:
  jsonRpcImage: "ECR_REGISTRY/fortify-json-rpc:GITHUB_HASH"
  ethereum:
    jsonRpcUrl: "https://cloudflare-eth.com"

trace:
  enabled: true
  ethereum:
    jsonRpcUrl: "ALCHEMY_URL"

query:
  queryImage: "ECR_REGISTRY/fortify-query:GITHUB_HASH"
  port: 8778
  db:
    path: "/tmp/fortify-alerts"

log:
  level: debug
  maxLogSize: 10m
  maxLogFiles: 10
