name: Go
description: Validate and test Go code
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.16
  - uses: actions/cache@v2
    with:
      path: |
        ~/go/pkg/mod
        ~/.cache/go-build
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-
  # - name: Install mockgen
  #   shell: bash
  #   run: go install github.com/golang/mock/mockgen@v1.5.0
  # - name: Build
  #   shell: bash
  #   run: go build -v ./...
  # - name: Run unit tests
  #   shell: bash
  #   run: make test
  - name: Prepare E2E test dependencies
    shell: bash
    run: |
      wget https://dist-dev.forta.network/dev-dependencies/geth
      chmod +x geth
      sudo cp geth /usr/bin/geth

      wget https://dist-dev.forta.network/dev-dependencies/ipfs
      chmod +x ipfs
      sudo cp ipfs /usr/bin/ipfs

      wget https://dist-dev.forta.network/dev-dependencies/disco
      chmod +x disco
      sudo cp disco /usr/bin/disco
  - name: Run E2E tests
    shell: bash
    run: make e2e-test
