name: 'Build and push images'
description: 'Build and push container images'
inputs:
  registry:
    description: 'Disco host'
    required: true
  name:
    description: 'Name of container to build'
    required: true
outputs:
  image-reference:
    description: 'Reference of the built and pushed image'
    value: ${{ steps.build-and-push.outputs.image-reference }}
runs:
  using: "composite"
  steps:
    - name: Login to Forta Disco
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: discouser
        password: discopass
    - name: Build and push container
      id: build-and-push
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.name }}
      run: |
        IMAGE_REF=$(./scripts/build-and-push.sh "$REGISTRY" "$IMAGE_NAME")
        echo "::set-output name=image-reference::$IMAGE_REF"
    - name: Build Manifest
      id: build-manifest
      shell: bash
      run: |
        ./scripts/build-manifest.sh  ./scripts/manifest-template.json manifest.json $GITHUB_SHA $IMAGE_REF
    - name: Push Manifest
      uses: aquiladev/ipfs-action@master
      id: ipfs
      with:
        path: ./manifest.json
        host: ipfs.forta.network
        port: 443
        protocol: https
        verbose: true