name: Go

on:
  pull_request:

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Validate and test Go code
        id: go
        uses: ./.github/actions/go
