name: Pull Request

on:
  pull_request:

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate and test Go code
        id: go
        uses: ./.github/actions/go
      - name: E2E Test
        id: e2e
        uses: ./.github/actions/e2e