name: Release Dev

on:
  push:
    branches: [master]
  workflow_dispatch:
    branches: [master]
  pull_request:

jobs:
  release:
    name: Release dev
    runs-on: ubuntu-18.04
    environment: dev
    defaults:
      run:
        working-directory: _release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for making tag detection work
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Find tag revision
        id: latest-tag-rev
        run:
          TAG_REV=$(git rev-list -n 1 ${{ steps.latest-tag.outputs.tag }})
          echo $TAG_REV
          echo "::set-output name=revision::$TAG_REV"
      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          version: ${{ steps.latest-tag.outputs.tag }}
          revision: ${{ steps.latest-tag-rev.outputs.revision }}
          aws_access_key: ${{ secrets.DEV_RELEASE_AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.DEV_RELEASE_AWS_SECRET_KEY }}
          build_artifacts_bucket_name: dev-forta-build-artifacts
          release_artifacts_bucket_name: dev-forta-releases
          release_artifacts_url: https://dist-dev.forta.network/artifacts
          dist_base_url: https://dist-dev.forta.network
          pgp_key_name: ${{ secrets.DEV_PGP_KEY_NAME }}
          pgp_private_key: ${{ secrets.DEV_PGP_PRIVATE_KEY }}
          pgp_public_key: ${{ secrets.DEV_PGP_PUBLIC_KEY }}
          pgp_passphrase: ${{ secrets.DEV_PGP_PASSPHRASE }}
