name: Upgrade Dev

on:
  push:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  containers:
    name: Build and push containers
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      node-image-ref: ${{ steps.write-output.outputs.node-image-ref }}
    strategy:
      matrix:
        image-name: [
          "node"
        ]
    steps:
      - name: Clear artifacts
        uses: kolpav/purge-artifacts-action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push container
        id: build-and-push
        uses: ./.github/actions/build-push
        with:
          registry: disco-dev.forta.network
          name: ${{ matrix.image-name }}
      - name: Write image reference as output
        id: write-output
        run: echo "::set-output name=${{ matrix.image-name }}-image-ref::${{ steps.build-and-push.outputs.image-reference }}"

  build-deploy:
    name: Build CLI and deploy
    needs: containers
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Clear artifacts
        uses: kolpav/purge-artifacts-action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build CLI and deploy
        id: build-and-deploy
        uses: ./.github/actions/build-deploy
        with:
          node-image-ref: ${{ needs.containers.outputs.node-image-ref }}
          deploy-aws-access-key: ${{ secrets.DEV_DEPLOY_AWS_ACCESS_KEY }}
          deploy-aws-secret-key: ${{ secrets.DEV_DEPLOY_AWS_SECRET_KEY }}
          deploy-aws-region: us-east-1
          release-aws-access-key: ${{ secrets.DEV_RELEASE_AWS_ACCESS_KEY }}
          release-aws-secret-key: ${{ secrets.DEV_RELEASE_AWS_SECRET_KEY }}
          release-aws-region: us-east-1
          build-artifacts-bucket-name: ${{ secrets.DEV_BUILD_ARTIFACTS_BUCKET_NAME }}
          run-codedeploy: false
